# Generated by Django 3.0.6 on 2020-06-03 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=7)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.CharField(max_length=10)),
                ('associated_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TodoList')),
            ],
        ),
    ]
