# Generated by Django 3.0.6 on 2020-06-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='color',
            field=models.CharField(default='#eee', max_length=7),
            preserve_default=False,
        ),
    ]
