# Generated by Django 3.0.6 on 2020-06-04 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todoitem_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='associated_list',
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
